### ISSUE TITLE
Not Issue !!!! Suggestion for amazing developer

### ISSUE THREAD

**Issue by bqytallhsirlkm** [persian-calendar/DroidPersianCalendar#571] opened 2020-07-13 09:33 UTC
**Salam Alaikum.
First, I would thank you for your grateful works**

  
1.  my suggestion about notification if you add a local notification that notifies the user on the day of events that can be modified by the user reminder the user for example on the 6-7.......etc clock.

2.    Also, this great app should have a 3D compass AR.

that is it ^_^ Allah blesses you.

**Comment by ebraminio** [comment] 2020-07-13 14:20
Hi. Thank you very much. About the first one guess you should just set time on events you are adding using Google Calendar when you are adding new appointments. About the second one, some issue on AR part as its needs for permission, but 3d one, nice one :) The problem is I don't have a device featuring compass sensor at all nowadays to develop the feature, but had one in 2012! I should see what can I do, thanks :)

**Comment by ebraminio** [comment] 2021-09-14 22:24
As explained is a bit complicated and out of scope but please don't hesitate bring your other suggestions. Thanks! :)

**Closed by ebraminio** 2021-09-14 22:24 UTC
